IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'EmployeeExist')
	DROP PROCEDURE EmployeeExist
GO
CREATE PROCEDURE [dbo].[EmployeeExist] 
(
@EmpId varchar(100)
)
AS
BEGIN 
		
	SELECT * FROM TBLEMPLOYEEMASTER WHERE employeeId =   @EmpId
END


