IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'GetAssinedMenuListAsperRole')
	DROP PROCEDURE GetAssinedMenuListAsperRole
GO
CREATE PROCEDURE [dbo].[GetAssinedMenuListAsperRole] (@UserId varchar(50))
AS
BEGIN 

	SELECT		MAINMENU_ID AS MainMenuId, 
				MAINMENU_NAME AS MenuName,       
				MAINMENU_DESC  AS [DESC] 
	FROM TBLMAINMENU    
	
	SELECT 
			SEC_SUBMENU.SUBMENU_ID as SUBMENU_ID, 
			SEC_SUBMENU.SUBMENU_NAME as SubMenuName,    
			SEC_SUBMENU.SUBMENU_URL AS SubMenuUrl,     
			SEC_SUBMENU.SUBMENU_DESC as [DESC],    
			SEC_MAINMENU.MAINMENU_ID AS MainMenuId    
	FROM TBLSUBMENU as SEC_SUBMENU
	LEFT OUTER JOIN TBLMAINMENU  AS SEC_MAINMENU 
	ON SEC_SUBMENU.MAINMENU_ID = SEC_MAINMENU.MAINMENU_ID
END