IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE 
ROUTINE_NAME = 'GetMenuSubMenuList')
	DROP PROCEDURE GetMenuSubMenuList
GO
--execute GetMenuSubMenuList 
CREATE PROCEDURE [dbo].[GetMenuSubMenuList] (@MainMenu_Id int = null)
AS
BEGIN 
	
	SELECT 
			SEC_SUBMENU.SUBMENU_ID as SUBMENU_ID, 
			SEC_SUBMENU.SUBMENU_NAME as SubMenuName,    
			SEC_SUBMENU.SUBMENU_URL AS SubMenuUrl,     
			SEC_SUBMENU.SUBMENU_DESC as [DESC],    
			SEC_MAINMENU.MAINMENU_ID AS MainMenuId    
	FROM	TBLSUBMENU as SEC_SUBMENU
	LEFT OUTER JOIN TBLMAINMENU  AS SEC_MAINMENU 
	ON		SEC_SUBMENU.MAINMENU_ID = SEC_MAINMENU.MAINMENU_ID
	WHERE  (@MainMenu_Id is null or SEC_MAINMENU.MAINMENU_ID = @MainMenu_Id)
	ORDER BY SEC_MAINMENU.DISPLAY_ORDER ASC, SEC_SUBMENU.DISPLAY_ORDER ASC
	
	
	SELECT MAINMENU_ID, MAINMENU_NAME, MAINMENU_DESC, DISPLAY_ORDER FROM TBLMAINMENU
	WHERE   (@MainMenu_Id is null or MAINMENU_ID = @MainMenu_Id) 
	UNION 
	SELECT 0 AS MAINMENU_ID, 'All' AS MAINMENU_NAME, 'DESC' AS  MAINMENU_DESC, 0 AS DISPLAY_ORDER
	ORDER BY DISPLAY_ORDER ASC	
END