CREATE VIEW [dbo].[VIEW_DELETE] AS
SELECT ADDACTION.ROLE_ID, ADDACTION.SUBMENU_ID, ADDACTION.ACTION_ID AS [DELETE]  
FROM tblRoleSubMenuConfig  ADDACTION LEFT OUTER JOIN TBLACTIONS ACT
ON ADDACTION.ACTION_ID = ACT.ACTION_ID 
WHERE ACT.ACTION_CODE = 'DELETE'


GO


