CREATE VIEW [dbo].[VIEW_ADD] AS
SELECT ADDACTION.ROLE_ID, ADDACTION.SUBMENU_ID, ADDACTION.ACTION_ID AS [ADD]  
FROM tblRoleSubMenuConfig  ADDACTION LEFT OUTER JOIN TBLACTIONS ACT
ON ADDACTION.ACTION_ID = ACT.ACTION_ID 
WHERE ACT.ACTION_CODE = 'ADD'
GO


