IF  EXISTS (SELECT * FROM sys.objects  WHERE object_id = OBJECT_ID('tblActions') 
AND type ='U')  DROP TABLE tblActions
GO
CREATE TABLE  tblActions
(		
		
		ACTION_ID			INT CONSTRAINT ACTION_ID PRIMARY KEY ,
		ACTION_CODE			VARCHAR(20) CONSTRAINT UK_ACTION_CODE UNIQUE, 
		ACTION_DESC			VARCHAR(1000), 
		ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
		ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
		UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
		UPDATE_TIMESTAMP	DATETIME,		
		[VERSION]		INT	)
Go

INSERT INTO TBLACTIONS (ACTION_ID,ACTION_CODE, ACTION_DESC, ADD_USERID, ADD_TIMESTAMP,
[VERSION]) VALUES (1, 'ADD','FOR ADD', NULL,GETDATE(),0)
GO
INSERT INTO TBLACTIONS(ACTION_ID,ACTION_CODE, ACTION_DESC, ADD_USERID, ADD_TIMESTAMP,
[VERSION]) VALUES (2, 'EDIT','FOR EDIT', NULL,GETDATE(),0)
GO
INSERT INTO TBLACTIONS (ACTION_ID,ACTION_CODE, ACTION_DESC, ADD_USERID, ADD_TIMESTAMP,
[VERSION]) VALUES (3, 'VIEW','FOR VIEW/SEARCH ', NULL,GETDATE(),0)
GO
INSERT INTO TBLACTIONS (ACTION_ID,ACTION_CODE, ACTION_DESC, ADD_USERID, ADD_TIMESTAMP,
[VERSION]) VALUES (4, 'DELETE','FOR DELETE', NULL,GETDATE(),0)


