IF  EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID('tblMainMenu') 
AND type ='U')DROP TABLE tblMainMenu
CREATE TABLE tblMainMenu
(
	MAINMENU_ID	INT IDENTITY(1,1) CONSTRAINT PK_MENU_ID PRIMARY KEY,
	MAINMENU_NAME	VARCHAR(50) CONSTRAINT UK_SEC_MAINMENU_NAME UNIQUE,
	MAINMENU_DESC	VARCHAR(100),
	ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
	ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
	UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
	UPDATE_TIMESTAMP	DATETIME,		
	[VERSION]		INT,
	DISPLAY_ORDER INT		
	)
Go
INSERT INTO dbo.tblMainMenu 
(MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('System Admin', 'System Admin', NULL, '08/16/2012 06:06:09 PM', NULL, NULL, NULL,0)
GO

INSERT INTO dbo.tblMainMenu (MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('My Info', 'My Info', NULL, '08/16/2012 06:06:09 PM', NULL, NULL,null,  0)
GO

INSERT INTO dbo.tblMainMenu 
(MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('Separation', 'Separation', null, '08/16/2012 06:06:09 PM', NULL, NULL, NULL,0)
GO

INSERT INTO dbo.tblMainMenu 
(MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('BCM', 'BCM', null, '08/16/2012 06:06:09 PM', NULL, NULL, NULL,0)
GO

INSERT INTO dbo.tblMainMenu 
(MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('Library Management', 'Library Management', null, '08/16/2012 06:06:09 PM', NULL, NULL, NULL,0)
GO

INSERT INTO dbo.tblMainMenu 
(MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('Travel', 'Travel', null, '08/16/2012 06:06:09 PM', NULL, NULL, NULL,0)
GO

INSERT INTO dbo.tblMainMenu
(MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('Inventory', 'Inventory', null, '08/16/2012 06:06:09 PM', NULL, NULL, NULL,0)
GO

INSERT INTO dbo.tblMainMenu 
(MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('Intercom', 'Intercom', null, '08/16/2012 06:06:09 PM', NULL, NULL, NULL,0)
GO

INSERT INTO dbo.tblMainMenu 
(MAINMENU_NAME, MAINMENU_DESC, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP, [VERSION],DISPLAY_ORDER)
VALUES ('Tax Exemption', 'Tax Exemption', null, '09/11/2012 03:20:17 PM', NULL, NULL, NULL,0)
GO