IF  EXISTS (SELECT * FROM sys.objects  WHERE object_id = OBJECT_ID('tblSubMenu')  AND type ='U')
DROP TABLE tblSubMenu
GO
CREATE TABLE  tblSubMenu
(		
		SUBMENU_ID			INT IDENTITY (1,1) CONSTRAINT SUBMENU_ID PRIMARY KEY ,
		SUBMENU_NAME		VARCHAR(50) CONSTRAINT UK_SUB_MENU_NAME UNIQUE,
		SUBMENU_DESC		VARCHAR(100),	
		SUBMENU_URL			VARCHAR(1000),	
		MAINMENU_ID		   INT FOREIGN KEY REFERENCES TBLMAINMENU(MAINMENU_ID),
		ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
		ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
	UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
	UPDATE_TIMESTAMP	DATETIME,		
	[VERSION]		INT,
	DISPLAY_ORDER INT,
	[STATUS] INT 	)		
Go

INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Create Role','~/RoleConfigurationSearch.aspx',1,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Role Menu Configuration','~/RoleConfigurationSearch.aspx',1,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Employee Role Mapping','~/RoleConfigurationSearch.aspx',1,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('My Info','~/RoleConfigurationSearch.aspx',2,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Update History','~/RoleConfigurationSearch.aspx',2,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Change Password','~/RoleConfigurationSearch.aspx',2,NULL,0,0)

INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Configure Approvers','~/RoleConfigurationSearch.aspx',1,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Initiate Resignation','~/RoleConfigurationSearch.aspx',3,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Assign Co-Ordinator','~/RoleConfigurationSearch.aspx',4,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Assign Caller','~/RoleConfigurationSearch.aspx',4,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('UnAssign Caller','~/RoleConfigurationSearch.aspx',4,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('View Assign Co-Ordinator','~/RoleConfigurationSearch.aspx',4,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('View Vendor Contact Detail','~/RoleConfigurationSearch.aspx',4,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Book Catalogue','~/RoleConfigurationSearch.aspx',5,NULL,0,0)

INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Book Return','~/RoleConfigurationSearch.aspx',5,NULL,0,0)

INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Book Issue','~/RoleConfigurationSearch.aspx',5,NULL,0,0)

INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Book Status','~/RoleConfigurationSearch.aspx',5,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Overdue Report','~/RoleConfigurationSearch.aspx',5,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Travel Report','~/RoleConfigurationSearch.aspx',6,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Travel Report Staff','~/RoleConfigurationSearch.aspx',6,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Assest Category','~/RoleConfigurationSearch.aspx',7,NULL,0,0)

INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Assest Type','~/RoleConfigurationSearch.aspx',7,NULL,0,0)


INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('Create Item','~/RoleConfigurationSearch.aspx',7,NULL,0,0)

INSERT INTO [TBLSUBMENU]([SUBMENU_NAME], [SUBMENU_URL] ,[MAINMENU_ID] ,[ADD_USERID],[VERSION],[DISPLAY_ORDER]) VALUES 
('View Intercom List','~/RoleConfigurationSearch.aspx',8,NULL,0,0)

