IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('tblRoles')  AND type ='U')
DROP TABLE tblRoles
GO
CREATE TABLE [dbo].[tblRoles](
	[ROLE_ID] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[ROLE_NAME] [varchar](50) NULL,
	[ROLE_DESC] [varchar](max) NULL,
	[DefaultRole] char(1)NULL,
	ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
	ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
	UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
	UPDATE_TIMESTAMP	DATETIME,		
	[VERSION]		INT			
)
go
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('Audit_tblRoles')  AND type ='U')
DROP TABLE Audit_tblRoles
GO
CREATE TABLE [dbo].[Audit_tblRoles](
	[ROLE_ID] [int] ,
	[ROLE_NAME] [varchar](50) NULL,
	[ROLE_DESC] [varchar](max) NULL,
	[DefaultRole] char(1)NULL,
	ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to USERS
	ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
	UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to USERS
	UPDATE_TIMESTAMP	DATETIME,		
	[VERSION]		INT			
)