IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('TBLERRORLOG')  AND type ='U')
DROP TABLE tblErrorLog
GO
CREATE TABLE [dbo].[tblErrorLog](
	[LogId] [int] IDENTITY(1,1) NOT NULL,
	[ExMessage] [varchar](1000) NULL,
	[StackTrace] [varchar](1000) NULL,
	[InnerException] [varchar](2000) NULL,
	[TargetSite] [varchar](1000) NULL,
	ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
	ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
	UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
	UPDATE_TIMESTAMP	DATETIME,		
	[VERSION]		INT		)