IF  EXISTS (SELECT * FROM sys.objects  WHERE object_id = OBJECT_ID('tblRoleSubMenuConfig') 
AND type ='U')
DROP TABLE tblRoleSubMenuConfig
GO
CREATE TABLE  tblRoleSubMenuConfig
(		
		ROLESUBMENUCONFIG_ID		INT IDENTITY (1,1) CONSTRAINT ROLESUBMENUCONFIG_ID PRIMARY KEY ,
		SUBMENU_ID					INT FOREIGN KEY REFERENCES TBLSUBMENU(SUBMENU_ID),							
		ROLE_ID	     				INT FOREIGN KEY REFERENCES TBLROLES(ROLE_ID),		
		ACTION_ID					INT FOREIGN KEY REFERENCES TBLACTIONS(ACTION_ID), 
		ADD_USERID					INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
		ADD_TIMESTAMP				DATETIME DEFAULT GETDATE(),		
		UPDATE_USERID				INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
		UPDATE_TIMESTAMP			DATETIME,		
		[VERSION]					INT	
)	
Go
IF  EXISTS (SELECT * FROM sys.objects  WHERE object_id = OBJECT_ID('Audit_tblRoleSubMenuConfig') 
AND type ='U')
DROP TABLE Audit_tblRoleSubMenuConfig
go
CREATE TABLE  Audit_tblRoleSubMenuConfig
(		
		ROLESUBMENUCONFIG_ID		INT ,
		SUBMENU_ID					INT FOREIGN KEY REFERENCES TBLSUBMENU(SUBMENU_ID),							
		ROLE_ID						INT FOREIGN KEY REFERENCES TBLROLES(ROLE_ID),	
		ACTION_ID					INT FOREIGN KEY REFERENCES TBLACTIONS(ACTION_ID), 	
		ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
		ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
		UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
		UPDATE_TIMESTAMP	DATETIME,		
		[VERSION]		INT	
)	
Go
