IF  EXISTS (SELECT * FROM sys.objects  WHERE object_id = OBJECT_ID('tblScreenActions') 
AND type ='U') DROP TABLE tblScreenActions
GO
CREATE TABLE  tblScreenActions
(		
		SCREENACTIONS_ID	INT IDENTITY (1,1) CONSTRAINT PK_SCREENACTIONS_ID PRIMARY KEY ,
		ACTION_ID			INT FOREIGN KEY REFERENCES  TBLACTIONS (ACTION_ID),
		SUBMENU_ID			INT FOREIGN KEY REFERENCES TBLSUBMENU(SUBMENU_ID),
		ROLE_ID				INT FOREIGN KEY REFERENCES TBLROLES(ROLE_ID),		
	    ADD_USERID			INT  FOREIGN KEY REFERENCES TBLUSERS([UID]) ,	
		ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
		UPDATE_USERID		INT  FOREIGN KEY REFERENCES TBLUSERS([UID]) ,	
		UPDATE_TIMESTAMP	DATETIME ,		
		UPDATE_COUNT		INT)	
Go

