IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('tblUsers')  AND type ='U')
DROP TABLE tblUsers
GO
CREATE TABLE  tblUsers
(		
		[UID]				INT IDENTITY (1,1) CONSTRAINT PK_UID PRIMARY KEY ,
		[USER_ID]			VARCHAR(50) CONSTRAINT UK_USER_ID UNIQUE,
		[USER_PASSWORD]  	VARCHAR(100),
		[IsFirstLogin]		[char](1) NULL,
		[LoginAttempt] [tinyint] NULL,
		[IsEnable] [char](1) NULL,
		EMP_ID				VARCHAR(500) , --INT  FOREIGN KEY REFERENCES EMP_STAFF_PERSON_DATA(EMP_ID),							
	    ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) ,	
		ADD_TIMESTAMP		DATETIME,		
		UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) ,	
		UPDATE_TIMESTAMP	DATETIME,		
		[VERSION]		    INT)	
Go
ALTER TABLE  TBLUSERS ADD  [login_date] [datetime] NULL
go
INSERT INTO tblUsers ([USER_ID], [USER_PASSWORD]) VALUES ('Dilip', 'test')
go
INSERT INTO tblUsers ([USER_ID], [USER_PASSWORD]) VALUES ('Kiran', 'test')
go
INSERT INTO tblUsers ([USER_ID], [USER_PASSWORD]) VALUES ('Amey', 'test')
