IF NOT EXISTS (SELECT  * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblbankdetails' AND COLUMN_NAME = 'isPrimaryAcc')
ALTER TABLE tblbankdetails
ADD  isPrimaryAcc CHAR(1)
GO 

IF NOT EXISTS (SELECT  * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblGrantApproval'AND  COLUMN_NAME = 'ApprovalStatus')
ALTER TABLE tblGrantApproval
ADD  ApprovalStatus INT FOREIGN KEY REFERENCES tblApprovalStatus(StatusId) DEFAULT 1 


IF NOT EXISTS (SELECT  * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblGrantApproval'AND  COLUMN_NAME = 'ApprovedBy')
ALTER TABLE tblGrantApproval
ADD  ApprovedBy INT FOREIGN KEY REFERENCES tblUsers(uid) DEFAULT NULL 


IF NOT EXISTS (SELECT  * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblGrantApproval'AND  COLUMN_NAME = 'ApprovedOn')
ALTER TABLE tblGrantApproval
ADD  ApprovedOn DATETIME
