IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('tblUserRoleConfig')  AND type ='U')
DROP TABLE tblUserRoleConfig
GO
CREATE TABLE [dbo].[tblUserRoleConfig](
	[User_Role_ID] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[ROLE_ID] [varchar](50) NULL ,
	[UID]				INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,
	ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
	ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
	UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
	UPDATE_TIMESTAMP	DATETIME,		
	[VERSION]		INT			
)
go
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('Audit_tblUserRoleConfig')  AND type ='U')
DROP TABLE Audit_tblUserRoleConfig
GO
CREATE TABLE [dbo].[Audit_tblUserRoleConfig](
	[User_Role_ID] [int], 
	[ROLE_ID] [varchar](50) NULL ,
	[UID]				INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,
	ADD_USERID			INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL,	--FK to SEC_USERS
	ADD_TIMESTAMP		DATETIME DEFAULT GETDATE(),		
	UPDATE_USERID		INT FOREIGN KEY REFERENCES TBLUSERS([UID]) NULL, --	FK to SEC_USERS
	UPDATE_TIMESTAMP	DATETIME,		
	[VERSION]		INT			
)